// <auto-generated />
using Lexical.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lexical.Migrations
{
    [DbContext(typeof(LexicalContext))]
    [Migration("20191030162421_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Lexical.Models.Word", b =>
                {
                    b.Property<int>("WordId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<double>("Rating");

                    b.Property<int>("RatingCount");

                    b.HasKey("WordId");

                    b.ToTable("Words");

                    b.HasData(
                        new
                        {
                            WordId = 1,
                            Name = "moist",
                            Rating = 2.0,
                            RatingCount = 1
                        },
                        new
                        {
                            WordId = 2,
                            Name = "damp",
                            Rating = 1.0,
                            RatingCount = 1
                        },
                        new
                        {
                            WordId = 3,
                            Name = "hug",
                            Rating = 4.0,
                            RatingCount = 1
                        },
                        new
                        {
                            WordId = 4,
                            Name = "burnt",
                            Rating = 5.0,
                            RatingCount = 1
                        },
                        new
                        {
                            WordId = 5,
                            Name = "vomit",
                            Rating = 1.0,
                            RatingCount = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
